version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_sem9
    environment:
      POSTGRES_DB: app_web_sem9
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin*2026
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    networks:
      - red-examen

  web:
    build: .
    container_name: apache_php_sem9
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_web_sem9
      - DB_USER=admin
      - DB_PASS=Admin*2026
    depends_on:
      - db
    networks:
      - red-examen

volumes:
  pgdata:

networks:
  red-examen:
    driver: bridge
